version: '3'
services:
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    volumes:
      - .:/bot_kenpo
    depends_on:
      - redis
    command: lita
    env_file:
      - ./.dockerenv
      - ./.dockerenv.secrets
    tty: true
    stdin_open: true
